### ISSUE TITLE
✍🏼 CRUD endpoints для сущности todo

### ISSUE THREAD

**Issue by auroraptor** [auroraptor/november-26#7]
Создать контроллер для каждого роута

- [x] `GET /users/me` возвращает информацию о пользователе (email и имя) 

- [x]  `PATCH /users/me` обновляет информацию о пользователе (email и имя) 

- [x]  `GET /items` возвращает весь список

- [x]  `GET/items/:page` возвращает страницу

- [x]  `POST /items` создает новый айтем

- [x] `PATCH /items/:id` обновляет информацию айтема по  id 

- [x] ` DELETE /items/:id` удаляет пункт по id 

- [x] Возможны фильтры
